---
title: "analysis"
author: "Anonymous"
date: "2025-10-25"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lme4)
library(dplyr)
library(readxl)
library(rmarkdown)
library(here)
output_fld = here::here("4.output")
out_data_fld = file.path(output_fld,"data")
code_fld = here::here("2.code")
```


```{r cars}
#______________________
# b) Multilevel model with random intercept for school, district, and student-level variance
#______________________
# Running this multilevel model to account for:
# 1. school variance - differences between schools
# 2. district variance - differences between districts 
# 3. student-level variance - differences between students withing schools

# load the data
merged_centered = file.path(out_data_fld,"df_merged_centered.xlsx")
df_merged_centered = read_excel(merged_centered) 

# transform the data in numeric
df_merged_centered <- df_merged_centered %>%
  mutate(
    reading_z = as.numeric(reading_z),
    math_z = as.numeric(math_z)
  )

# Multilevel model on reading z-scores
mixed_reading <- lmer(
  reading_z ~ factor(household_income_quintile) + female + rural +
    disability_status + parent_education_level + attendance_centered  +
    (1 | school_id) + (1 | district_id) + factor(year),
  data = df_merged_centered,
  weights = weight
)
# summarize the results -READING
summary(mixed_reading)

# Multilevel model on math z-scores
mixed_math <- lmer(
  math_z ~ factor(household_income_quintile) + female + rural +
    disability_status + parent_education_level + attendance_centered  +
    (1 | school_id) + (1 | district_id) + factor(year),
  data = df_merged_centered,
  weights = weight
)
# summarize the results - MATH
summary(mixed_math)

#______________________
# c) Prediction math and reading score given an increase in attendance due to the proposed intervention
#______________________
# Define values for prediction
sd_increase = 0.3
nbr_school_days = 190

# Simulate an increase of 0.3 for low-income students living in rural settings
df_sim <- df_merged_centered %>%
  mutate(attendance_centered = if_else(low_income == 1 & rural == 1, # low income represents households in the first and second quantale
                                       attendance_centered + sd_increase,
                                       attendance_centered))

# Predict outcomes using the mixed model
df_sim$reading_pred <- predict(mixed_reading, newdata = df_sim, re.form = NA)
df_sim$math_pred <- predict(mixed_math, newdata = df_sim, re.form = NA)

# Aggregate predicted outcomes by income quantile
sim_summary <- df_sim %>%
  group_by(household_income_quintile) %>%
  summarise(mean_reading_pred = mean(reading_pred),
            mean_math_pred = mean(math_pred))

print(sim_summary)

# mean and standard deviation of attendance
mean(df_merged_centered$attendance_rate, na.rm = TRUE)
sd(df_merged_centered$attendance_rate, na.rm = TRUE)

# presents results on school attendance

# % increase in attendance:
sd(df_merged_centered$attendance_rate, na.rm = TRUE)*sd_increase
# Increase in attendance days thanks to school feeding. Assuming 190 days of school:
sd(df_merged_centered$attendance_rate, na.rm = TRUE)*sd_increase*nbr_school_days



```



